site_name: Equinor AppSec
repo_url: https://github.com/equinor/appsec/
site_url: https://equinor.github.io/appsec/
site_author: ISC AppSec, Equinor ASA
site_description: >-
  Guidelines and tutorials related in Application Security in Equinor.

edit_uri: edit/main/docs
copyright: >
  Copyright &copy; Equinor ASA
theme:
  name: material
  custom_dir: overrides
  logo: assets/icons/appsec-icon-white.svg
  favicon: assets/icons/appsec-iconenergyred.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - navigation.top
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/equinor
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/EquinorASA
  consent:
    title: This website uses cookies
    description: >-
      We use cookies to recognize your visits, as well as to measure the effectiveness of our documentation and whether users find what they're searching for. With your consent, you're helping us to make our documentation better.

    actions:
      - accept
extra_css:
  - assets/css/mkdocs-eq.css
  - https://eds-static.equinor.com/font/equinor-font.css
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - admonition
  - toc:
        permalink: true
plugins:
    - search
    - awesome-pages
